### ISSUE TITLE
preal/wrela

### ISSUE THREAD

**Issue by fortunechen** [Gitsamshi/WeakVRD-Captioning#10]
Hi,Shi

I wonder what the keys:  `preal` and `wreal` mean  in file `dataloader.py`( line 283,285) ?

why there exist two kinds of above relationships.

**Comment by fortunechen** [comment]
The author has replied to me through email.

`prela is from https://github.com/yangxuntu/SGAE, which is extracted by pre-trained vrd model. wrela is extracted from our weakly supervised vrd model. Both wrela and prela share the same object information, therefore could be merged together.`

**Comment by n9705** [comment]
Hi, I still have a little confused that why the prela and wrela can just simply stack together, doesn't they have some same relations?

**Comment by Gitsamshi** [comment]
Hi, thanks for asking. There could be multiple relations between any two nodes, so I viewed "prela" and "wrela" as complementary to each other.

**Comment by n9705** [comment]
Thanks for reply, two nodes have multiple relations means that two nodes have more than one edge? I thought It has a little strange~
