### ISSUE TITLE
关于CGVRG的生成

### ISSUE THREAD

**Issue by llylll** [Gitsamshi/WeakVRD-Captioning#11]
作者您好，最近拜读了您的论文。论文中关于使用用coco中的描述句子和图片训练关系检测网络的想法非常的新颖，比其他论文中使用通用VRG检测器的方法精度提高很多。所以我想认真研究一下这部分的实现。但这个仓库中似乎之后后面解码器的部分代码，请问您能开源一下弱监督学习训练关系检测网络的这部分代码吗，万分感谢！

**Comment by Gitsamshi** [comment]
你好，

抱歉由于周末回复晚了，多谢关注！
对的，其它论文没有在COCO数据集上对VRG进一步对齐，尤其是对VRG中的predicate。CGVRG代码的是基于Neural Motif  (https://arxiv.org/abs/1711.06640)的github实现上修改的。

由于论文发表时，CGVRG模块代码的主要作者已经毕业，没来得及将具体内容整理给我。我之后联系他下，有进展会告诉你。

如有任何实现的问题，可以随时问我。多谢！

**Comment by llylll** [comment]
好的，十分感谢您！祝您工作生活愉快！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Gitsamshi/WeakVRD-Captioning"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月22日(星期一) 凌晨2:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Gitsamshi/WeakVRD-Captioning] 关于CGVRG的生成 (#11)





 
你好，
 
抱歉由于周末回复晚了，多谢关注！
 对的，其它论文没有在COCO数据集上对VRG进一步对齐，尤其是对VRG中的predicate。CGVRG代码的是基于Neural Motif  (https://arxiv.org/abs/1711.06640)的github实现上修改的。
 
由于论文发表时，CGVRG模块代码的主要作者已经毕业，没来得及将具体内容整理给我。我之后联系他下，有进展会告诉你。
 
如有任何实现的问题，可以随时问我。多谢！

**Comment by llylll** [comment]
> 你好，
> 
> 抱歉由于周末回复晚了，多谢关注！
> 对的，其它论文没有在COCO数据集上对VRG进一步对齐，尤其是对VRG中的predicate。CGVRG代码的是基于Neural Motif ([https://arxiv.org/abs/1711.06640)的github实现上修改的。](https://arxiv.org/abs/1711.06640)%E7%9A%84github%E5%AE%9E%E7%8E%B0%E4%B8%8A%E4%BF%AE%E6%94%B9%E7%9A%84%E3%80%82)
> 
> 由于论文发表时，CGVRG模块代码的主要作者已经毕业，没来得及将具体内容整理给我。我之后联系他下，有进展会告诉你。
> 
> 如有任何实现的问题，可以随时问我。多谢！

你好，请问多任务学习的词性标签是如何获取的呢？

**Comment by Gitsamshi** [comment]
你好，用textual scene graph parser提取的（https://nlp.stanford.edu/software/scenegraph-parser.shtml）或者在https://github.com/yangxuntu/SGAE提供的文件有提取好的。

**Comment by llylll** [comment]
好的谢谢

**Comment by llylll** [comment]
您好，想请教下目标检测提取object特征的步骤，您看看有没错。
首先使用在VG数据集上预训练的faster-RCNN得到图片中各个物体的框坐标以及他们的类别和置信度，然后根据类别和置信度进行NMS去重复的框，将剩下的框根据坐标裁切图片，送入预训练的resnet101中生成2048维的特征向量。一个框生成一个2048维的向量，一张图片有k个框则生成k*2048维的向量。

**Comment by Gitsamshi** [comment]
对的

**Comment by llylll** [comment]
你好，“scripts/prepro_feats.py”中的代码显示的全局图像特征fc_feats是由resnet提取的特征，decoder代码中写到将这个fc特征作为平均图像特征输入第一层LSTM。可论文中使用的平均图像特征似乎是GCN编码后的平均节点特征，似乎和代码不太相符，请问这是怎么回事呢？

**Comment by Gitsamshi** [comment]
多谢提问，主要两者结果差别不大，代码中graph node的feature也都有；直接load object regions的average features训练快一点。

**Comment by llylll** [comment]
好的谢谢！

**Comment by llylll** [comment]
您好，我打印了您提供的数据集中的标签句子和句子单词对应的词性，但似乎词性标签有点问题，和句子里的单词对应不上，您看看这个链接
[https://github.com/llylll/tmp/blob/main/20210630_1.png](url)

**Comment by Gitsamshi** [comment]
scenegraphparser应该是按phrase标注的，如果一个phrase没被detect出来，phrase中两个词都不会被tag出来

**Comment by llylll** [comment]
谢谢回答，那这样的话生成的词性感觉就不是很准，似乎会影响模型的精度？

**Comment by Gitsamshi** [comment]
phrase中的object一般能被一致的detect出来，那个两句话中不一致标注的应该是phrase中的形容词。

**Comment by llylll** [comment]
您好，不好意思再次打扰下您，请问这份代码要怎么在coco online test server上测试呢

**Comment by Gitsamshi** [comment]
please refer the last two lines of issue #12
