### ISSUE TITLE
关于论文相关问题

### ISSUE THREAD

**Issue by Linjz1** [Gitsamshi/WeakVRD-Captioning#13]
您好，我最近拜读了您的论文《Improving Image Captioning with Better Use of Captions》，我非常喜欢您的工作，但对Qualitative Analysis部分的实验有一些疑惑。比如Figure7的图一，场景图中出现了street，但左边的图片目标检测的结果似乎没有street这个物体，请问这是怎么回事呢？

**Comment by Gitsamshi** [comment]
Hi, thx for your interest. street 这个tag应该是对应图中那个绿色的街牌（Street sign）。
