### ISSUE TITLE
Code: Weak supervised multi-instance training

### ISSUE THREAD

**Issue by Monikshah** [Gitsamshi/WeakVRD-Captioning#18]
Can you please provide the code for weak supervised multi-instance training or if you have already uploaded, can you please provide the link to it?

Thank you

**Comment by Gitsamshi** [comment]
Thanks for asking. The CGVRG module is mainly by the second author, who has already graduated by the time the paper is accepted. I don't have that code at hand. But I know his code was modified from the neural motif repo. If you have any questions regarding implementation, pls feel free to leave a comment here.

**Comment by Monikshah** [comment]
Thank you very much for the response. 

I am trying to implement this module. I have extracted the data from images and sentences but I am stuck in forming the positive and negative bag. Please check #19  (I have written my question here).
