### ISSUE TITLE
Meeting unknown error when training with RL

### ISSUE THREAD

**Issue by tjuwyh** [Gitsamshi/WeakVRD-Captioning#4]
Hi, Gitsamshi!
I have meet this problem when I tried to train my model with RL and I cannot figure it out why it happens.
![image](https://user-images.githubusercontent.com/26714868/92107598-a8fcff80-ee18-11ea-9536-088717da3a81.png)

Since I actually totally follow your data setting and use the released data files, I don't think it's the issus about label categories (like some blogs said).
Do you have any idea on why this problem occurs or how to fix it?

**Comment by Gitsamshi** [comment]
I didn't meet with this error before. Seems like a CUDA error?
