### ISSUE TITLE
RL training ,keyerror

### ISSUE THREAD

**Issue by userpei** [Gitsamshi/WeakVRD-Captioning#6]
When I used RL training, there was a mistake.   How can I modify it?
Traceback (most recent call last):
  File "train.py", line 171, in <module>
    train(opt)
  File "train.py", line 102, in train
    reward = get_self_critical_reward(decoder, core_args, vrg_data, fc_feats, att_feats, weak_relas, att_masks, data, gen_result, opt)
  File "/peng/pyx/WeakVRD-Captioning-master/misc/rewards_graph.py", line 60, in get_self_critical_reward
    _, cider_scores = CiderD_scorer.compute_score(gts, res_)
  File "cider/pyciderevalcap/ciderD/ciderD.py", line 48, in compute_score
    (score, scores) = cider_scorer.compute_score(self._df)
  File "cider/pyciderevalcap/ciderD/ciderD_scorer.py", line 199, in compute_score
    score = self.compute_cider(df_mode)
  File "cider/pyciderevalcap/ciderD/ciderD_scorer.py", line 173, in compute_cider
    vec, norm, length = counts2vec(test)
  File "cider/pyciderevalcap/ciderD/ciderD_scorer.py", line 122, in counts2vec
    df = np.log(max(1.0, self.document_frequency[ngram]))
KeyError: ('5452', '1660')

**Comment by HN123-123** [comment]
> When I used RL training, there was a mistake. How can I modify it?
> Traceback (most recent call last):
> File "train.py", line 171, in
> train(opt)
> File "train.py", line 102, in train
> reward = get_self_critical_reward(decoder, core_args, vrg_data, fc_feats, att_feats, weak_relas, att_masks, data, gen_result, opt)
> File "/peng/pyx/WeakVRD-Captioning-master/misc/rewards_graph.py", line 60, in get_self_critical_reward
> _, cider_scores = CiderD_scorer.compute_score(gts, res_)
> File "cider/pyciderevalcap/ciderD/ciderD.py", line 48, in compute_score
> (score, scores) = cider_scorer.compute_score(self._df)
> File "cider/pyciderevalcap/ciderD/ciderD_scorer.py", line 199, in compute_score
> score = self.compute_cider(df_mode)
> File "cider/pyciderevalcap/ciderD/ciderD_scorer.py", line 173, in compute_cider
> vec, norm, length = counts2vec(test)
> File "cider/pyciderevalcap/ciderD/ciderD_scorer.py", line 122, in counts2vec
> df = np.log(max(1.0, self.document_frequency[ngram]))
> KeyError: ('5452', '1660')

**Comment by HN123-123** [comment]
Have you solved this problem? I also met the same error.
I want to kown how do you fit it.

**Comment by Monikshah** [comment]
How did you resolve this error?
