### ISSUE TITLE
Question about the TEST.

### ISSUE THREAD

**Issue by JingyuLi-code** [Gitsamshi/WeakVRD-Captioning#7]
Hi, thanks for your great work! 
     I want to know there's no Groundtruth caption in the test phase. How do you solve it and build CGVRG?

**Comment by n9705** [comment]
I thought when doing inference, the image should first go through the faster-RCNN network to detect the object regions, then these regions are combined pairwise and do through the relation-detect network to detect the relation. If the relation possibility is larger than a threshold, this object region has the relation and an edge will assign between them. Then the CGVRG can be bulid.
